# Generated by Django 5.1.5 on 2025-09-18 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
