# Generated by Django 5.1.5 on 2025-09-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_tag_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='genders',
        ),
        migrations.AddField(
            model_name='product',
            name='genders',
            field=models.ManyToManyField(blank=True, to='products.gender'),
        ),
    ]
