# Generated by Django 5.1.5 on 2025-09-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_gender_remove_product_genders_product_genders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genders',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AddField(
            model_name='product',
            name='genders',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
